### PR TITLE
Fix fromString

### LINKED ISSUE #38: Numberformatexception can escape your `fromString` function
```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

import java.util.UUID
UUID.fromString("2630147c-4a18-4866-9bbd-b2d89acef83z")

// Exiting paste mode, now interpreting.

java.lang.NumberFormatException: For input string: "b2d89acef83z"
  at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
  at java.lang.Long.parseLong(Long.java:589)
  at java.lang.Long.valueOf(Long.java:776)
  at java.lang.Long.decode(Long.java:928)
  at java.util.UUID.fromString(UUID.java:206)
  ... 44 elided
```

this makes the `fromEither` function impure

### PR DESCRIPTION
**Pull request by d1skort**
Hi! I wanna close #38

### CODE REVIEW

**Comment by ChristopherDavenport** [comment]
Hmm that totally shouldn't pass bincompat.

**Comment by d1skort** [comment]
Thank you for review. What can I done here? Maybe exists another way for fix this issue?

**Comment by ChristopherDavenport** [comment]
@d1skort  I think we could use a translate error to work.

```scala
Either.catchNonFatal(x)
  .adaptError{
     case ok@IllegalArgumentException => ok
     case other                       => new IllegalArgumentException(other.getMessage)
  }
```

**Comment by ChristopherDavenport** [comment]
Honestly that may be the better solution overall.

**Comment by ChristopherDavenport** [comment]
This may be 
`ok : IllegalArgumentException => ok.asInstanceOf[IllegalArgumentException]`

We will be changing the type explicitly to throwable in next version but I agree we should fix this here initially.

**Comment by d1skort** [comment]
Interesting...
Thank you for support!

**Comment by ChristopherDavenport** [comment]
One final thing, could we introduce a test to make sure the original concern is addressed and will continue to be addressed moving forward.

Same as [this](https://github.com/ChristopherDavenport/fuuid/blob/master/modules/core/src/test/scala/io/chrisdavenport/fuuid/FUUIDSpec.scala#L10) test but with the input - `2630147c-4a18-4866-9bbd-b2d89acef83z`

**Comment by d1skort** [comment]
yeah, totally

**Pull request merged**
